### ISSUE TITLE
Broken link in lesson content

### ISSUE THREAD

**Issue by rrombom** [learn-co-curriculum/cs-implementing-an-arraylist-lab#3]
In the last sentence of the lesson: "Once you have your implementation working, compare it to mine, which you can find by checking out the solutions branch of the repo, **or you can read it on GitHub**."

The final clause is a link that doesn't lead anywhere. 

(Is it supposed to go here? https://github.com/learn-co-students/cs-implementing-an-arraylist-lab-codeU/tree/solution)

**Comment by AnnJohn** [comment]
should be fixed now. thanks.
